# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    ls $(System.DefaultWorkingDirectory)/arm
  displayName: 'Run a multi-line script'

- task: azsdktm.AzSDK-task.azsk-cicd-armchecker.AzSKARMTemplateChecker@4
  displayName: 'AzSK_ARMTemplateChecker '
  inputs:
    ARMTemplateFilePath: '$(System.DefaultWorkingDirectory)\arm'
    ExcludeFiles: '$(System.DefaultWorkingDirectory)\arm\enable-activity-log-diagnostics.json' # This is a __subscription__ deployment and those currently don't work with the ARM Template Checker